stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  IMAGE_NAME: "appimages"
  CONTAINER_NAME: "app-container"
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.6.3-jdk-8-openj9
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - pwd
    - mvn  clean package -DskipTests=true $MAVEN_OPTS package 
  only:
    # 只对master分支运行job
    - master
  artifacts:
    expire_in: 1 week
    paths:
      # 可以指定到某个文件(这里指定到了jar包)，或者整个target/目录 可以用于下载
      - target/renren-fast.jar  
job_deploy:
    image: docker
    stage: deploy
    script:
      - docker build -t ${IMAGE_NAME} .
      - if [ $(docker ps -aq --filter name=${CONTAINER_NAME}) ]; then docker rm -f ${CONTAINER_NAME};fi
      - docker run -d -p 8080:80 --name ${CONTAINER_NAME} ${IMAGE_NAME}  
      # 删除为none的images    
      - docker rmi $(docker images | awk '/^<none>/ { print $3 }')
job_copy:
    image: docker
    stage: deploy
    before_script:
        - 'which ssh-agent || ( yum update -y && yum install openssh-client git -y ) '
        - eval $(ssh-agent -s)
        - echo $SSH_PRIVATE_KEY  |  base64 -d
        - echo $SSH_PRIVATE_KEY  |  base64 -d
        - echo $SSH_PRIVATE_KEY  |  base64 -d | ssh-add -
        # - cat id_rsa |  base64 -w0
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan  -p 28488  45.62.123.30 > ~/.ssh/known_hosts  //xxxx替换为远程服务器的地址
        - chmod 644 ~/.ssh/known_hosts
    script:
       - ssh -p 28488 45.62.123.30  'echo aa >>  /tmp/tmp.txt'
       # - ssh -p 28488 45.62.123.30  mkdir /tmp/deploy1
       - scp -P 28488 -r target/* 45.62.123.30:/tmp/      
