stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  IMAGE_NAME: "appimages"
  CONTAINER_NAME: "app-container"
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.6.3-jdk-8-openj9
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - pwd
    - mvn  clean package -DskipTests=true $MAVEN_OPTS package 
  only:
    # 只对master分支运行job
    - master
  artifacts:
    expire_in: 1 week
    paths:
      # 可以指定到某个文件(这里指定到了jar包)，或者整个target/目录 可以用于下载
      - target/renren-fast.jar  
job_deploy:
    image: docker
    stage: deploy
    script:
      - docker build -t ${IMAGE_NAME} .
      - if [ $(docker ps -aq --filter name=${CONTAINER_NAME}) ]; then docker rm -f ${CONTAINER_NAME};fi
      - docker run -d -p 8080:80 --name ${CONTAINER_NAME} ${IMAGE_NAME}  
      # 删除为none的images    
      - docker rmi $(docker images | awk '/^<none>/ { print $3 }')
